language: ruby
env:
  - BUNDLER_VERSION=1.3.5
  - BUNDLER_VERSION=1.5.1
  - BUNDLER_VERSION=1.3.5 BUNDLER_ARGS=--standalone
  - BUNDLER_VERSION=1.5.1 BUNDLER_ARGS=--standalone
  - BUNDLER_VERSION=1.3.5 BUNDLER_ARGS=--deployment
  - BUNDLER_VERSION=1.5.1 BUNDLER_ARGS=--deployment
  - BUNDLER_VERSION=1.3.5 BUNDLER_ARGS=--local
  - BUNDLER_VERSION=1.5.1 BUNDLER_ARGS=--local
rvm:
  - rbx
before_install:
  - mkdir -p vendor/cache
  - cd vendor/cache
  - gem fetch rubinius-bundler-canary
before_script:
  - rvm @global do gem uninstall bundler -ax
  - gem install bundler -v $BUNDLER_VERSION
script:
  - bundle --version
  - bundle install $BUNDLER_ARGS
  - bundle exec rubinius-bundler-canary
